# Generated by Django 3.1.4 on 2020-12-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
